name = "sophon-chunks"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = ""

[[rules]]
type = "Text"
globs = ["**/*.json"]

[[r2_buckets]]
binding = "SOPHON_CHUNKS"
bucket_name = "sophon-chunks"