name: Update Sophon Chunk Endpoint

on:
    schedule:
        - cron: '0 * * * *'

jobs:
    update-endpoint:
        permissions:
            contents: read
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            - name: Update Content
              run: |
                  bun run update-chunks
